name: Build ReOpenHack

on:
  push:
    branches:
      - "**" # This ensures it runs no matter what your branch is named
  workflow_dispatch: # This allows you to click "Run Workflow" manually in the Actions tab

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  geode:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest

    name: Geode ReOpenHack
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          ccache-variant: ''
          export-pdb: true
          build-config: ${{env.BUILD_TYPE}}
          configure-args: "-DBUILD_STANDALONE=OFF"

  package-geode:
    name: Package Geode Mod
    runs-on: ubuntu-latest
    needs: ['geode']

    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReOpenHack-Geode
          path: ${{ steps.build.outputs.build-output }}
